$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $repoRoot

$required = @(
  "README.md",
  "LICENSE",
  ".gitignore",
  "fixtures/cases.csv",
  "examples/extended_cases.csv",
  "metadata/project.json",
  "docs/operations.md",
  "docs/extension-plan.md",
  "scripts/verify.ps1"
)

foreach ($path in $required) {
  if (-not (Test-Path $path)) {
    throw "missing required file: $path"
  }
}

$readme = Get-Content -Raw README.md
if ($readme.Contains([char]0x2014)) {
  throw "README contains an em dash"
}

$banned = @(
  "created by codex",
  "generated by ai",
  "co-authored-by",
  "co-authored by",
  "as an ai",
  "artificial intelligence"
)
$lower = $readme.ToLowerInvariant()
foreach ($term in $banned) {
  if ($lower.Contains($term)) {
    throw "README contains banned wording: $term"
  }
}

$metadata = Get-Content -Raw metadata/project.json | ConvertFrom-Json
if (-not $metadata.name -or -not $metadata.model.threshold) {
  throw "metadata/project.json is missing required fields"
}

$fixtures = Import-Csv fixtures/cases.csv
$extended = Import-Csv examples/extended_cases.csv
if ($fixtures.Count -lt 3) {
  throw "fixtures/cases.csv must contain at least 3 cases"
}
if ($extended.Count -lt 6) {
  throw "examples/extended_cases.csv must contain at least 6 cases"
}

& powershell -NoProfile -ExecutionPolicy Bypass -File scripts/verify.ps1
