$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $root

$repo = "atlas-ops-rename-map"
$focus = "dry-run spread"

if (-not (Test-Path "README.md")) { throw "$repo is missing README.md" }
if (-not (Test-Path "fixtures/domain_review.csv")) { throw "$repo is missing domain review cases" }
if (-not (Test-Path "metadata/domain-review.json")) { throw "$repo is missing domain review metadata" }

$readme = Get-Content -Raw README.md
if ($readme.Contains([char]0x2014)) { throw "$repo README contains an em dash" }
foreach ($term in @("script-assisted", "batch upload", "generated by ai", "created by codex", "co-authored-by")) {
  if ($readme.ToLowerInvariant().Contains($term)) { throw "$repo README contains blocked wording: $term" }
}

$domain = Get-Content -Raw metadata/domain-review.json | ConvertFrom-Json
if ($domain.repo -ne $repo) { throw "$repo metadata points at a different repo" }
if (-not (($domain.review_model.terms -join "|").Contains($focus))) { throw "$repo missing expected focus term" }

& powershell -NoProfile -ExecutionPolicy Bypass -File "scripts/check-atlas-ops-rename-detail.ps1"
& powershell -NoProfile -ExecutionPolicy Bypass -File scripts/verify.ps1
